name: IndexNow

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Send IndexNow Request
        run: |
          curl -v "https://www.bing.com/indexnow?url=https://drsolve.github.io/&key=${{ secrets.INDEXNOW_KEY }}"
